name: Karmiconomy
main: com.mitsugaru.Karmiconomy.Karmiconomy
description: Economy suppliment plugin, to provide payments based on actions.
version: 0.15
author: Mitsugaru
depend: [Vault]
softdepend: [PlayerPoints, mcMMO, Heroes]

commands:
  kcon:
    description: Root command

permissions:
  Karmiconomy.admin:
    description: Administrate plugin
    default: op